# Generated by Django 4.2.6 on 2023-10-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_report_created_time_report_generated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='store_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='store_id',
            field=models.CharField(max_length=255),
        ),
    ]
